import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from '@/components/header/header';
import ProfileCard from '@/components/ProfileCard/profileCard';
import SearchBar from '@/components/SearchBar/searchBar';
import FeaturedJobs from '@/components/FeaturedJobs/featuredJobs';
import styles from './dashboard.module.css';

export default function Home() {

  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`mainWrapper`}>
        <Header />
        <div className={styles.dashboard}>
          <aside className={styles.sidebar}>
            <ProfileCard />
          </aside>
          <main className={styles.main}>
            <SearchBar />
            <FeaturedJobs />
          </main>
        </div>
      </main>
    </>
  );
}
